# Basic site settings
title: Water Service Contract Form
description: Online form for water service contract in Lisbon Metropolitan Area

# Ensure HTML files are processed correctly
include:
  - index.html

# Prevent Jekyll from processing certain files
exclude:
  - README.md
  - LICENSE

# Set default layout
defaults:
  - scope:
      path: ""
    values:
      layout: default
